# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  schedule:
    - cron: '0 0 * * *'
  watch: 
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    
    if: github.actor == github.event.repository.owner.login
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: config
        run: |
          git config --global user.email "add your github email here"
          git config --global user.name "nomoney4me"
      - run: npm install
      
      - name: Fetch new data
        run: node index.js
      
      - name: Update files in ./output/
        uses: actions-js/push@master
        with:
          message: Updated epg
          github_token: ${{ secrets.GITHUB_TOKEN }}
